default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: sample_review_development
test:
  <<: *default
  database: sample_review_test
production:
  <<: *default
  database: sample_review_production
  username: sample_review
  password: <%= ENV['SAMPLE_REVIEW_DATABASE_PASSWORD'] %>
